title: Adel wael ahmed
logo: /assets/img/cropped_profile_img.png

description: Data Scientist

show_downloads: False

phone_number: 01004742088
address: Cairo, Egypt
email: eslam.mo.atia@gmail.com
linkedin_username: eKor
github_username: eKorayem

#google_analytics:

theme: jekyll-theme-minimal
